Repository SWM-Space-Odyssey/WeddingMate_BackEnd, pull requests merged in 2023-10, with the labels that each got.

#115 [SO-270] hotfix : docker image ecr에 pull/push 로직 추가
  .github/workflows/deploy.yml
  Dockerfile
  appspec.yml
  build.gradle
  config/scripts/deploy.sh
  docker-compose.prod.yml
Labels: 😊머지가능

#113 [SO-271] refactor: 순환 참조를 피하기 위해 service 계층에서 repository 관련 로직 분리
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/service/ChatRoomsService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/service/CompaniesRepositoryService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/repository/FilesRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/service/FilesRepositoryService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/service/FilesService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/service/ImageFilesValidator.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/service/ItemsRepositoryService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/repository/LikesRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/LikesRepositoryService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioDetailResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/service/PortfolioRepositoryService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/service/PortfolioService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/PlannerProfilesController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/repository/PlannerProfilesRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/CustomerProfilesService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/ProfileRepositoryService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/ProfilesFilesUploadService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/AuthService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/CustomersService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/PlannersService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/UsersService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/repositoryservice/CustomersRepositoryService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/repositoryservice/PlannersRepositoryService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/repositoryservice/UsersRepositoryService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/jwt/JwtTokenProvider.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/utils/CookieUtils.java
Labels: 🛠refactor, 😊머지가능

#114 [SO-141] feat: soft delete로 회원 탈퇴 구현
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/entity/Files.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/entity/Items.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/repository/ItemsRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/service/ItemsService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/entity/UserLikes.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/enums/LikeEnum.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/LikesService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/entity/Portfolios.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/repository/PortfoliosRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/entity/PlannerProfiles.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/PlannerProfilesService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/ProfilesService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/controller/AuthController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/controller/SignupController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Customers.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Planners.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Users.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/repository/CustomersRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/repository/PlannersRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/SecurityConfig.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
Labels: 😊머지가능, 💪수정요청

#119 [SO-269] feat : CodeDeploy를 활용한 CD 파이프라인 분리
  .github/workflows/deploy.yml
Labels: 😊머지가능

#120 [SO-276] feat : AOP, Custom Annotation으로 코드 성능 측정
  Dockerfile
  build.gradle
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/entity/UserLikes.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/enums/LikeEnum.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/LikesService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/SecurityConfig.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/annotation/LogExecutionTime.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/annotation/TimeTraceAop.java
Labels: 😊머지가능

#122 [SO-273] feat: Springdoc을 이용한 swagger 추가
  build.gradle
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/controller/ChatMessagesController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/controller/ChatRoomsController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/dto/ChatRoomDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/dto/ChatRoomResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/entity/ChatMessages.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/entity/ChatRooms.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/entity/Companies.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/controller/FilesController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/entity/Files.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/controller/ItemsController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/controller/ItemsFilesUploadController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/controller/LikesController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/controller/PortfoliosController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/CustomerProfilesController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/MypageProfilesController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/MypageProfilesFilesUploadController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/PlannerProfilesController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/controller/AuthController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/controller/SignupController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Customers.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/SecurityConfig.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/swagger/SwaggerConfig.java
  src/main/resources/application-swagger.yml
  src/main/resources/application.yml
Labels: 😊머지가능

#124 [SO-273] fix: swagger url 수정
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/SecurityConfig.java
Labels: 🐇Simple

#130 [SO-288] fix: codedeploy 스크립트 수정
  .github/workflows/deploy.yml
  appspec.yml
  config/codedeploy/beforeInstall.sh
Labels: 👀리뷰필요

#128 [SO-287] refactor : serviceImpl 패턴으로 likeService 개선
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/entity/Companies.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/entity/Items.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/mapper/ItemsMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/controller/LikesController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/dto/LikeReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/enums/LikeEnum.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/CompanyLikeImpl.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/ItemLikeImpl.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/LikeActionService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/LikesService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/PlannerLikeImpl.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/PortfolioLikeImpl.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/entity/Portfolios.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/mapper/PortfoliosMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/PlannerProfilesService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Planners.java
Labels: 😊머지가능

#132 [SO-285] feat : redis를 이용한 분산락 구현 및 테스트
  build.gradle
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/CompanyLikeImpl.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/ItemLikeImpl.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/LikeActionService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/LikesService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/PlannerLikeImpl.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/PortfolioLikeImpl.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/aop/DistributedLock/AopForTransaction.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/aop/DistributedLock/CustomSpringELParser.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/aop/DistributedLock/DistributedLock.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/aop/DistributedLock/DistributedLockAop.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/aop/ExecutionTime/LogExecutionTime.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/aop/ExecutionTime/TimeTraceAop.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/redis/RedissonConfig.java
  src/main/resources/application-test.yml
  src/test/java/swmaestro/spaceodyssey/weddingmate/container/RedisTestContainer.java
  src/test/java/swmaestro/spaceodyssey/weddingmate/domain/like/LikeService/LikeLockTest.java
  src/test/java/swmaestro/spaceodyssey/weddingmate/domain/like/repository/LikeRepositoryTest.java
  src/test/resources/application-cloud.yml
  src/test/resources/application-dev.yml
  src/test/resources/application-oauth.yml
  src/test/resources/application-test.yml
  src/test/resources/application.yml
Labels: 👀리뷰필요

#133 [SO-298] feat: 카카오 로그인 시 gender와 age 추가
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/KakaoOAuth2User.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/OAuth2UserInfo.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/service/CustomOAuth2UserService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/controller/SignupController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Users.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/enums/UserAccountStatusEnum.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
Labels: 👀리뷰필요

#136 [SO-300] fix : 운영서버 배포 파이프라인 로직 수정
  .github/workflows/deploy_prod.yml
  config/scripts/deploy_prod.sh
  docker-compose.prod.yml
  docker-compose.yml
Labels: 👀리뷰필요

#138 [SO-300] hotfix : ecr repository명 수정
  .github/workflows/deploy_prod.yml
Labels: 👀리뷰필요

#139 hotfix : v2 관련 hotfix 반영(#138)
  .github/workflows/deploy_prod.yml
Labels: 👀리뷰필요

#140 [SO-301] fix: oauth.yml에 성별, 연령대 추가
  src/main/resources/application-oauth.yml
Labels: bug, 🐇Simple, 👀리뷰필요

#141 [SO-301] feat: 성별, 연령대 추가 (#140)
  src/main/resources/application-oauth.yml
Labels: 👀리뷰필요

#142 [SO-128] feat: 신고, 정지 API 및 @Scheduled를 사용한 정지 해제 구현
  build.gradle
  src/main/java/swmaestro/spaceodyssey/weddingmate/WeddingmateApplication.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/report/controller/ReportController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/report/dto/ReportByReportedResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/report/dto/ReportByReporterResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/report/dto/ReportReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/report/entity/Report.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/report/enums/ReportItemType.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/report/enums/ReportReason.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/report/mapper/ReportMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/report/repository/ReportRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/report/service/ReportService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/report/service/UserSuspensionReleaseService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/report/service/UserSuspensionService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/controller/SignupController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Users.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/enums/SuspensionPeriodEnum.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/enums/UserAccountStatusEnum.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/repository/UsersRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/UsersService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/repositoryservice/UsersRepositoryService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/test/DummyEntity.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/UserConstant.java
  src/test/java/swmaestro/spaceodyssey/weddingmate/domain/report/controller/ReportControllerTest.java
  src/test/java/swmaestro/spaceodyssey/weddingmate/domain/report/service/ReportServiceTest.java
  src/test/java/swmaestro/spaceodyssey/weddingmate/domain/report/service/UserSuspensionServiceTest.java
Labels: 😊머지가능
