Repository SWM-Space-Odyssey/WeddingMate_BackEnd, pull requests merged in 2023-09, with the labels that each got.

#89 [SO-209] 채팅방 CRD & 실시간 채팅 API 추가
  build.gradle
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/controller/ChatMessageController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/controller/ChatRoomController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/dto/ChatMessageDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/dto/ChatMessageReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/dto/ChatMessageResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/dto/ChatRoomDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/dto/ChatRoomResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/entity/ChatMessage.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/entity/ChatRoom.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/enums/MessageType.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/pubsub/RedisPublisher.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/pubsub/RedisSubscriber.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/repository/ChatMessageRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/repository/ChatRoomRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/service/ChatMessageService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/chat/service/ChatRoomService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/UsersService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/SecurityConfig.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/jackson/JackSonConfig.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/redis/RedisConfig.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/stomp/WebSocketConfig.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/chat/ChatRoomNotAuthorizedException.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/chat/ChatRoomNotFoundException.java
Labels: 😊머지가능

#90 [SO-232] style: planner, customer 지역 리스트 변수 이름 regionList로 변경
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/dto/PlannerInfoDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/dto/CustomerSignupReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Customer.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Planner.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/mapper/CustomerMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/mapper/PlannerMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/test/DummyEntity.java
Labels: 🐇Simple, 😊머지가능

#92 [SO-244] hotfix : ecr 관련 로직 제거
  .github/workflows/deploy.yml
  config/scripts/deploy.sh
Labels: 😊머지가능

#94 [SO-247] hotfix : 포트폴리오 디테일에서 플래너 프로필 아이디 반환
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/mapper/PortfoliosMapper.java
Labels: 🐇Simple, 😊머지가능

#96 [SO-248] hotfix : 삭제된 아이템의 피드 이미지 제외
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/repository/FilesRepository.java
Labels: bug, 😊머지가능

#95 [SO-145] feat : item 검색 시 full text search 적용 및 pagination 추가
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/controller/ItemsController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/mapper/ItemsMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/repository/ItemsRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/service/ItemsService.java
Labels: 😊머지가능

#97 [SO-227] hotfix: refresh token 쿠키에서 읽어오도록 수정
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/controller/AuthController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/AuthService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/SecurityConfig.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/ErrorCode.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/token/RefreshTokenCookieNotFoundException.java
Labels: bug, 😊머지가능

#98 [SO-200] feat : 배포 서버 github actions 워크플로우 추가
  .github/workflows/deploy_prod.yml
Labels: 👀리뷰필요

#100 [SO-200] fix : 운영 서버 환경변수 분리
  .github/workflows/deploy_prod.yml
Labels: 🐇Simple, 👀리뷰필요

#101 [SO-200] fix : 운영 서버 환경변수 분리
  .github/workflows/deploy_prod.yml
Labels: 👀리뷰필요

#102 [SO-265] fix : redirect url 환경변수로 분리
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/SecurityConfig.java
Labels: 👀리뷰필요

#105 [SO-242] feat : customer 수정 api 추가
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/MypageProfilesController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/PlannerProfilesController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/dto/CustomerInfoDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/dto/CustomerProfileUpdateReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/PlannerProfilesService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/ProfilesService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Customers.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/mapper/CustomersMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/SecurityConfig.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
Labels: 😊머지가능

#106 [SO-256] feat : Compaines Entity 추가 및 아이템과 연결
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/entity/Companies.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/repository/CompaniesRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/service/CompaniesService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/dto/ItemResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/dto/ItemSaveReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/dto/ItemUpdateReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/entity/Items.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/mapper/ItemsMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/repository/ItemsRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/service/ItemsService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Customers.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/test/DummyEntity.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/company/CompanyNotFoundException.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/ErrorCode.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/GlobalExceptionHandler.java
Labels: 👀리뷰필요

#107 [SO-266] hotfix : file Entity에서 is_deleted 관련 처리 추가
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/entity/Files.java
Labels: 🐇Simple, 👀리뷰필요

#108 [SO-267] fix: userlike에 is_deleted 관련 로직 추가
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/entity/UserLikes.java
Labels: bug, 🐇Simple, 👀리뷰필요

#109 [SO-268] feat : 업체 좋아요 기능 추가
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/company/entity/Companies.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/controller/LikesController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/dto/CompanyLikeResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/entity/UserLikes.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/enums/LikeEnum.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/mapper/LikesMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/LikesService.java
Labels: 💪수정요청
