Repository SWM-Space-Odyssey/WeddingMate_BackEnd, pull requests merged in 2023-08, with the labels that each got.

#41 [SO-147] feat : 사용하지 않는 docker image 삭제, AWS ECR로 백업
  .github/workflows/deploy.yml
  config/scripts/delete.sh
  config/scripts/deploy.sh
Labels: 😊머지가능

#43 [SO-143] feat: CookieUtil 추가 및 Token refresh api 추가
  .idea/workspace.xml
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/service/CookieAuthorizationRequestRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/service/CustomOAuth2UserService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/controller/AuthController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/AuthService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/SecurityConfig.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/utils/CookieUtils.java
Labels: 😊머지가능

#47 [SO-151] refactor: 파일 업로드 과정 리팩토링 및 검증 추가
  build.gradle
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/controller/FileController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/dto/FileInfoDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/dto/FileResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/enums/FilePathType.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/enums/ImageExtensionType.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/service/FileService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/service/FileUploadService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/service/ImageFileValidator.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/service/PortfolioService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/S3/S3Config.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/S3/S3Uploader.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/file/FileNameEmptyException.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/file/FileNotImageException.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/file/FileUnSupportedExtensionTypeException.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/file/FileUploadFailureException.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/ErrorCode.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/GlobalExceptionHandler.java
Labels: 🛠refactor, 😊머지가능

#52 [SO-148] feat: API 공통 응답 포맷 생성
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/category/controller/CategoryController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/controller/FileController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/controller/ItemController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/controller/PortfolioController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/UserProfileController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/tag/controller/TagController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/controller/AuthController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/dto/ApiResponse.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/dto/ApiResponseStatus.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/ErrorResponse.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/GlobalExceptionHandler.java
Labels: 🐇Simple

#56 [SO-161] refactor : 포트폴리오, 아이템 태그 코드 리팩토링 및 테스트
  .idea/workspace.xml
  build.gradle
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/controller/FileController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/service/FileService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/controller/ItemController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/dto/ItemMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/dto/ItemOrderDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/dto/ItemResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/dto/ItemSaveReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/dto/ItemUpdateReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/entity/Item.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/mapper/ItemMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/service/ItemService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/service/CookieAuthorizationRequestRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/controller/PortfolioController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioDetailResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioSaveReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioTagMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioUpdateReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/entity/Portfolio.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/mapper/PortfolioMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/service/PortfolioService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/UserProfileController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/mapper/CustomerMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/SecurityConfig.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/GlobalExceptionHandler.java
  src/main/resources/application-test.yml
  src/main/resources/db/teardown.sql
  src/test/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/PortfolioDummyEntity.java
  src/test/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/controller/PortfolioControllerTest.java
  src/test/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/service/PortfolioServiceTest.java
  src/test/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/test.jpg
Labels: 😊머지가능

#59 [SO-177] refactor: 각 기능 안에서 파일 API를 처리하도록 수정
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/controller/FileController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/dto/ItemFileReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/service/FileUploadService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/controller/ItemFileUploadController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/dto/ItemFileReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/service/ItemFileUploadService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/service/ItemService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/service/CustomOAuth2UserService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/controller/PortfolioController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioSaveReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioUpdateReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/service/PortfolioFileUploadService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/service/PortfolioService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/UserProfileFileUploadController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/ProfileFileUploadService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Users.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/GlobalExceptionHandler.java
  src/test/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/controller/PortfolioControllerTest.java
Labels: bug, 🛠refactor, 😊머지가능

#61 [SO-182] refactor: 플래너, 예비부부의 Tag를 String으로 변경 및 매개변수 개수 감소
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/entity/ItemTag.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/entity/PortfolioTag.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/mapper/PortfolioTagMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/tag/controller/TagController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/tag/dto/TagMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/tag/dto/TagResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/tag/entity/Tag.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/tag/repository/TagRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/tag/service/TagService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/dto/CustomerSignupReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/dto/CustomerTagListDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/dto/PlannerSignupReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Customer.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Planner.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/PlannerTag.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/mapper/CustomerMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/mapper/PlannerMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/mapper/PlannerTagMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/repository/PlannerTagRepository.java
Labels: 🛠refactor, 👀리뷰필요

#60 [SO-181] feat : 포트폴리오 및 아이템 디테일 조회 시 isWriter 키 추가
  .idea/workspace.xml
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/controller/ItemController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/dto/ItemResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/mapper/ItemMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/service/ItemService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/controller/PortfolioController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioDetailResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/mapper/PortfolioMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/service/PortfolioService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/test/DummyEntity.java
  src/test/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/controller/PortfolioControllerTest.java
  src/test/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/service/PortfolioServiceTest.java
Labels: 😊머지가능

#64 [SO-184] hotfix : 지역태그 추가 및 DummyEntity에서 UserLike 삭제
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioDetailResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/mapper/PortfolioMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/test/DummyEntity.java
Labels: 🐇Simple

#65 [SO-185] feat: PR 라벨 추가 및 삭제 workflow 추가
  .github/workflows/add_review_label_on_open.yml
  .github/workflows/remove_labels_on_close.yml
Labels: 😊머지가능

#66 [SO-185] feat: workflow 체크용 PR
  .github/workflows/add_review_label_on_open.yml
  .github/workflows/remove_labels_on_close.yml
Labels: 👀리뷰필요

#68 [SO-185] fix: PR 관련 github flow 외부 라이브러리 사용하도록 수정
  .github/workflows/add_review_label_on_open.yml
  .github/workflows/remove_labels_on_close.yml
Labels: 💻수정반영중

#70 [SO-179] fix: 플래너 단일 프로필 조회 body -> param으로 수정 및 마이페이지 프로필 API 추가
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/PlannerProfileController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/UserProfileController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/dto/PlannerProfileReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/dto/PlannerProfileUpdateReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/PlannerProfileService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/ProfileService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Users.java
Labels: 😊머지가능

#72 [SO-187] feat: 플래너 프로필 태그 수정 추가
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/MypageProfileController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/MypageProfileFileUploadController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/dto/PlannerProfileUpdateReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/dto/PlannerProfileUpdateResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/mapper/ProfileMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/ProfileService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Planner.java
Labels: 👀리뷰필요

#73 [SO-186] feat : 플래너 포트폴리오 리스트 api 추가 및 plannerId 키 추가
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioDetailResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/mapper/PortfolioMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/PlannerProfileController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/PlannerProfileService.java
Labels: 😊머지가능

#74 [SO-195] fix: 유저 프로필 사진이 변경되지 않는 문제 해결
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/file/service/FileUploadService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/ProfileFileUploadService.java
Labels: bug, 😊머지가능

#75 [SO-196] fix : item update시 기존 파일과의 연결 해제
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/service/ItemService.java
Labels: bug, 👀리뷰필요

#79 [SO-197] fix : portfolio update 시 파일 필수 제거
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/controller/PortfolioController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/service/PortfolioService.java
Labels: 🐇Simple, 👀리뷰필요

#82 [SO-84] feat : 좋아요 기능 추가 및 테스트
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/controller/LikeController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/dto/LikeReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/dto/PlannerLikeResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/dto/PortfolioLikeResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/entity/UserLike.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/enums/LikeEnum.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/mapper/LikeMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/repository/LikeRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/LikeService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/repository/UsersRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/test/DummyEntity.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/ErrorCode.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/like/LikeTypeNotSupportedException.java
  src/test/java/swmaestro/spaceodyssey/weddingmate/domain/like/repository/LikeRepositoryTest.java
Labels: 👀리뷰필요

#83 [SO-207] refactor : 포트폴리오 entity 연결 관계 user에서 planner로 변경
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/service/ItemService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/controller/PortfolioController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/entity/Portfolio.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/mapper/PortfolioMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/service/PortfolioService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/PlannerProfileService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Planner.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Users.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/test/DummyEntity.java
  src/test/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/controller/PortfolioControllerTest.java
  src/test/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/service/PortfolioServiceTest.java
Labels: 😊머지가능

#84 [SO-212] feat : 좋아요 isLiked 반환 및 count 추가
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/dto/ItemResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/entity/Item.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/mapper/ItemMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/service/ItemService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/controller/LikeController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/mapper/LikeMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/repository/LikeRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/like/service/LikeService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioDetailResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioListResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/entity/Portfolio.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/mapper/PortfolioMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/service/PortfolioService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/PlannerProfileController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/dto/PlannerProfileResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/PlannerProfileService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Planner.java
Labels: 😊머지가능

#86 [SO-228] hotfix : likecount setter 중복 제거
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/entity/Item.java
Labels: 🐇Simple, 👀리뷰필요
