Repository SWM-Space-Odyssey/WeddingMate_BackEnd, pull requests merged in 2023-07, with the labels that each got.

#9 feat : Feature/so-30 배포 자동화 flow 추가
  .github/workflows/deploy.yml
  Dockerfile
  config/nginx/Dockerfile
  config/nginx/nginx.conf
  config/scripts/deploy.sh
  docker-compose.prod.yml
  docker-compose.yml
  src/main/resources/application.yml
Labels: 😊머지가능

#10 [SO-34] feat: 카카오 소셜로그인으로 회원가입 처리
  .gitattributes
  .gitignore
  build.gradle
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/KakaoOAuth2User.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/OAuth2UserInfo.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/OAuth2UserInfoFactory.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/UserPrincipal.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/enums/AuthProvider.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/repository/CookieAuthorizationRequestRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/service/CustomOAuth2UserService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/service/CustomUserDetailsService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/utils/CookieUtils.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/AuthUsers.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Users.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/enums/UserEnum.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/repository/UsersRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/SecurityConfig.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/jwt/JwtAccessDeniedHandler.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/jwt/JwtTokenProvider.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/ErrorCode.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/GlobalExceptionHandler.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/ErrorCode.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/ErrorResponse.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/oauth2/OAuth2AuthProviderIdNotFoundException.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/oauth2/OAuth2DuplicateEmailException.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/oauth2/OAuthUnAuthURLException.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/users/UserNameNotFoundException.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/users/UserNotFoundException.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/properties/AppProperties.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/properties/OAuth2ClientProperties.java
  src/main/resources/application.yml
Labels: 👀리뷰필요

#15 [SO-93] feat : Category, Tag 엔티티 추가
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/category/entity/Category.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/tag/entity/Tag.java
Labels: 😊머지가능

#25 [SO-116] redis server
  config/redis/Dockerfile
  config/redis/redis.conf
  docker-compose.prod.yml
Labels: 😊머지가능

#24 [SO-118] hotfix : AuthUser 에러 해결
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/UserPrincipal.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/oauth2/service/CustomUserDetailsService.java
Labels: 😊머지가능

#26 [SO-93] feat : portfolio 생성, 조회 기능 추가
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/category/repository/CategoryRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/controller/PortfolioController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/ItemMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/ItemResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/ItemSaveReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioDetailResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioListResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioSaveReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioSaveResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/entity/Item.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/entity/ItemTag.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/entity/Portfolio.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/entity/PortfolioTag.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/repository/ItemRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/repository/PortfolioRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/service/PortfolioService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/tag/dto/TagMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/tag/dto/TagResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/tag/entity/Tag.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/tag/repository/TagRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Users.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/category/CategoryNotFoundException.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/ErrorCode.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/portfolio/PortfolioNotFoundException.java
Labels: 😊머지가능

#28 [SO-93] refactor : item directory 분리
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/controller/ItemController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/dto/ItemMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/dto/ItemResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/dto/ItemSaveReqDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/entity/Item.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/entity/ItemTag.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/service/ItemService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/controller/PortfolioController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/ItemMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/ItemResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/dto/PortfolioDetailResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/entity/Portfolio.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/repository/ItemRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/service/PortfolioService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/config/SecurityConfig.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/ErrorCode.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/portfolio/ItemNotFoundException.java
Labels: 🐇Simple, 😊머지가능

#31 [SO-95] feat : portoflio delete api 추가
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/category/dto/CategoryMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/controller/ItemController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/dto/ItemMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/dto/ItemResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/entity/Item.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/item/service/ItemService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/controller/PortfolioController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/entity/Portfolio.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/portfolio/service/PortfolioService.java
Labels: 😊머지가능

#34 [SO-89] feat: 플래너 프로필 생성, 조회, 수정 API 추가
  .idea/workspace.xml
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/controller/UserProfileController.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/dto/PlannerProfileResDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/dto/PlannerProfileUpdateDto.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/entity/PlannerProfile.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/mapper/ProfileMapper.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/repository/PlannerProfileRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/profile/service/ProfileService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/entity/Planner.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/repository/PlannerRepository.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/domain/users/service/UsersService.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/constant/ResponseConstant.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/ErrorCode.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/profile/PlannerProfileNotFoundException.java
  src/main/java/swmaestro/spaceodyssey/weddingmate/global/exception/users/PlannerNotFoundException.java
Labels: 😊머지가능
